chemflow/jobs/urls.py
from django.urls import path
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from chemflow.jobs.views import (
    job_list_view,
    job_create_dock_view,
    job_create_score_view,
    job_detail_view,
    job_delete_view
)

app_name = "jobs"
urlpatterns = [
    path("", view=job_list_view, name="list"),
    path("new/docking", view=job_create_dock_view, name="create_dock"),
    path("new/rescoring", view=job_create_score_view, name="create_score"),
    path("<str:pk>/", view=job_detail_view, name="detail"),
    path("<str:pk>/delete", view=job_delete_view, name="delete"),
]

urlpatterns += staticfiles_urlpatterns()

chemflow/users/urls.py
from django.urls import path

from chemflow.users.views import (
    user_list_view,
    user_redirect_view,
    user_update_view,
    user_detail_view,
)

app_name = "users"
urlpatterns = [
    path("", view=user_list_view, name="list"),
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

config/urls.py
from django.conf import settings
from django.urls import include, path
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views

urlpatterns = [
    path("", TemplateView.as_view(template_name="pages/home.html"), name="home"),
    path(
        "about/",
        TemplateView.as_view(template_name="pages/about.html"),
        name="about",
    ),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # Job management
    path(
        "jobs/",
        include("chemflow.jobs.urls", namespace="jobs")
    ),
    # User management
    path(
        "users/",
        include("chemflow.users.urls", namespace="users"),
    ),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
] + static(
    settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

chemflow/jobs/models.py
import os
from django.db import models
from django.conf import settings
from django_celery_results.models import TaskResult

# from .tasks import run_dock, run_score


def user_directory_path(instance, filename):
    # file will be uploaded to MEDIA_ROOT/user_<id>/<filename>
    return f'user_{instance.owner.username}/{filename}'


class Job(models.Model):
    job_type = models.CharField(max_length=50, blank=True)
    job_name = models.CharField(max_length=100,  blank=True)
    project_name = models.CharField(max_length=50, blank=True)
    protocol_name = models.CharField(max_length=50, blank=True)
    sf = models.CharField(max_length=50, default='vina')

    receptor_file = models.FileField(upload_to=user_directory_path)
    receptor_name = models.CharField(max_length=100,  blank=True)
    ligands_file = models.FileField(upload_to=user_directory_path)
    ligands_name = models.CharField(max_length=100, blank=True)

    center_x = models.FloatField(blank=True, null=True)
    center_y = models.FloatField(blank=True, null=True)
    center_z = models.FloatField(blank=True, null=True)

    radius = models.FloatField(blank=True, null=True)

    size_x = models.FloatField(blank=True, null=True)
    size_y = models.FloatField(blank=True, null=True)
    size_z = models.FloatField(blank=True, null=True)

    created_at = models.DateTimeField(auto_now_add=True, blank=True)
    updated_at = models.DateTimeField(auto_now=True, blank=True)
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, blank=True)
    state = models.CharField(max_length=50, default='0')
    job_task = models.CharField(max_length=100, blank=True, null=True)
    postprocess_task = models.CharField(max_length=100, blank=True, null=True)

    def __str__(self):
        return self.job_name

    def save(self, force_insert=False, force_update=False, using=None,
             update_fields=None):
        super(Job, self).save(force_insert=False, force_update=False, using=None,
                              update_fields=None)

        if self.state == 'RUNNING':
            try:
                self.state = TaskResult.objects.get(task_id=self.job_task).status
                self.save()
            except TaskResult.DoesNotExist:
                pass

        elif self.state == 'POST PROCESSING':
            if self.postprocess_task:
                try:
                    state = TaskResult.objects.get(task_id=self.postprocess_task).status
                    if state == 'SUCCESS':
                        self.state = 'POST PROCESS'
                        self.save()
                except TaskResult.DoesNotExist:
                    pass

chemflow/users/forms.py
from django.contrib.auth import get_user_model, forms
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _

User = get_user_model()


class UserChangeForm(forms.UserChangeForm):

    class Meta(forms.UserChangeForm.Meta):
        model = User


class UserCreationForm(forms.UserCreationForm):

    error_message = forms.UserCreationForm.error_messages.update(
        {"duplicate_username": _("This username has already been taken.")}
    )

    class Meta(forms.UserCreationForm.Meta):
        model = User

    def clean_username(self):
        username = self.cleaned_data["username"]

        try:
            User.objects.get(username=username)
        except User.DoesNotExist:
            return username

        raise ValidationError(self.error_messages["duplicate_username"])

chemflow/jobs/views.py
import os
import shutil
import tarfile
from wsgiref.util import FileWrapper
import mimetypes

from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import DetailView, ListView, CreateView, DeleteView
from django.urls import reverse
from django.conf import settings
from django.http import HttpResponse
from django.utils.encoding import smart_str

from .models import Job
from .forms import JobDockForm, JobScoreForm
from .tasks import run_dock, run_score, postprocess_dock, postprocess_score


class JobCreateView(LoginRequiredMixin, CreateView):
    model = Job
    slug_field = "job_type"
    slug_url_kwarg = "job_type"

    def post(self, request, *args, **kwargs):
        request.POST = request.POST.copy()
        request.POST['owner'] = request.user.id
        request.POST['state'] = '0'
        request.POST['job_name'] = request.POST.get('project_name') + " - " + request.POST.get('protocol_name')
        request.POST['receptor_name'] = str(request.FILES['receptor_file']).split('.')[0]
        request.POST['ligands_name'] = str(request.FILES['ligands_file']).split('.')[0]
        return super(JobCreateView, self).post(request, *args, **kwargs)

    def get_success_url(self):
        return reverse("jobs:list")

    def form_valid(self, form):
        user_jobs = list(Job.objects.filter(owner=self.request.user,
                                            job_type=self.request.POST.get('job_type'),
                                            job_name=self.request.POST.get('job_name')))
        if len(user_jobs) > 0:
            form.add_error('job_name', u'You already have a job with the same name. Please change the project or protocol name.')
            return self.form_invalid(form)

        return super(JobCreateView, self).form_valid(form)


class JobCreateDockView(JobCreateView):
    form_class = JobDockForm

    def post(self, request, *args, **kwargs):
        request.POST = request.POST.copy()
        request.POST['job_type'] = 'dock'

        return super(JobCreateDockView, self).post(request, *args, **kwargs)

    def form_valid(self, form):
        return super(JobCreateDockView, self).form_valid(form)


job_create_dock_view = JobCreateDockView.as_view()


class JobCreateScoreView(JobCreateView):
    form_class = JobScoreForm

    def post(self, request, *args, **kwargs):
        request.POST = request.POST.copy()
        request.POST['job_type'] = 'score'

        return super(JobCreateScoreView, self).post(request, *args, **kwargs)

    def form_valid(self, form):
        return super(JobCreateScoreView, self).form_valid(form)


job_create_score_view = JobCreateScoreView.as_view()


class JobListView(LoginRequiredMixin, ListView):
    model = Job
    slug_field = "job_name"
    slug_url_kwarg = "job_name"

    def get(self, request, *args, **kwargs):
        for object in self.get_queryset():
            if object.state == '0':
                workdir = os.path.join(settings.MEDIA_ROOT, 'user_' + object.owner.username)
                project_name = object.project_name
                protocol_name = object.protocol_name
                receptor_file_path = os.path.basename(str(object.receptor_file))
                ligands_file_path = os.path.basename(str(object.ligands_file))
                center_x = str(object.center_x)
                center_y = str(object.center_y)
                center_z = str(object.center_z)
                sf = object.sf
                if object.job_type == 'dock':
                    job = run_dock.delay(workdir,
                                         project_name,
                                         protocol_name,
                                         receptor_file_path,
                                         ligands_file_path,
                                         center_x,
                                         center_y,
                                         center_z,
                                         sf)
                else:
                    job = run_score.delay(workdir,
                                          project_name,
                                          protocol_name,
                                          receptor_file_path,
                                          ligands_file_path,
                                          center_x,
                                          center_y,
                                          center_z,
                                          sf)
                # TODO: put the PENDING status here and change it to RUNNING when the task is RUNNING (task.py)
                object.state = "RUNNING"
                object.job_task = str(job)
                object.save()
            else:
                object.save()
        return super(JobListView, self).get(request, *args, **kwargs)


job_list_view = JobListView.as_view()


class JobDetailView(LoginRequiredMixin, DetailView):
    model = Job
    slug_field = "job_name"
    slug_url_kwarg = "job_name"

    def get(self, request, *args, **kwargs):
        object = self.get_object()
        object.save()
        workdir = os.path.join(settings.MEDIA_ROOT, 'user_' + object.owner.username)
        receptor_file_path = os.path.basename(str(object.receptor_file))
        ligands_file_path = os.path.basename(str(object.ligands_file))

        if request.GET.get('postprocess'):
            if object.job_type == 'dock':
                postprocess = postprocess_dock.delay(workdir,
                                                     object.project_name,
                                                     object.protocol_name,
                                                     receptor_file_path,
                                                     ligands_file_path,
                                                     object.center_x,
                                                     object.center_y,
                                                     object.center_z,
                                                     object.sf)
            else:
                postprocess = postprocess_score.delay(workdir,
                                                      object.project_name,
                                                      object.protocol_name,
                                                      receptor_file_path,
                                                      ligands_file_path,
                                                      object.center_x,
                                                      object.center_y,
                                                      object.center_z,
                                                      object.sf)
            object.postprocess_task = str(postprocess)
            object.state = 'POST PROCESSING'
            object.save()

        if request.GET.get('download'):
            pass
            # Compress the results in a tar file
            # tar = tarfile.open("sample.tar.bz2", "w:bz2")
            # for name in ["file1", "file2", "file3"]:
            #     tar.add(name)
            # tar.close()

        if request.GET.get('download_receptor'):
            file_path = os.path.join(workdir, receptor_file_path)
            file_wrapper = FileWrapper(open(file_path, 'rb'))
            file_mimetype = mimetypes.guess_type(file_path)
            response = HttpResponse(file_wrapper, content_type=file_mimetype)
            response['X-Sendfile'] = file_path
            response['Content-Length'] = os.stat(file_path).st_size
            response['Content-Disposition'] = 'attachment; filename=%s' % smart_str(object.receptor_name + '.' + receptor_file_path.split('.')[-1])
            return response

        if request.GET.get('download_ligands'):
            file_path = os.path.join(workdir, ligands_file_path)
            file_wrapper = FileWrapper(open(file_path, 'rb'))
            file_mimetype = mimetypes.guess_type(file_path)
            response = HttpResponse(file_wrapper, content_type=file_mimetype)
            response['X-Sendfile'] = file_path
            response['Content-Length'] = os.stat(file_path).st_size
            response['Content-Disposition'] = 'attachment; filename=%s' % smart_str(object.ligands_name + '.' + ligands_file_path.split('.')[-1])
            return response

        if request.GET.get('download_docking'):
            file_path = os.path.join(workdir, object.project_name + '.chemflow', 'DockFlow', object.protocol_name, receptor_file_path.split('.')[0], 'docked_ligands.mol2')
            file_wrapper = FileWrapper(open(file_path, 'rb'))
            file_mimetype = mimetypes.guess_type(file_path)
            response = HttpResponse(file_wrapper, content_type=file_mimetype)
            response['X-Sendfile'] = file_path
            response['Content-Length'] = os.stat(file_path).st_size
            response['Content-Disposition'] = 'attachment; filename=%s' % smart_str('docked_ligands.mol2')
            return response

        if request.GET.get('download_energy'):
            if object.job_type == 'dock':
                file_path = os.path.join(workdir, object.project_name + '.chemflow', 'DockFlow', object.protocol_name, receptor_file_path.split('.')[0], 'DockFlow.csv')
                file_name = 'DockFlow.csv'
            else:
                file_path = os.path.join(workdir, object.project_name + '.chemflow', 'ScoreFlow', object.protocol_name, receptor_file_path.split('.')[0], 'ScoreFlow.csv')
                file_name = 'ScoreFlow.csv'
            file_wrapper = FileWrapper(open(file_path, 'rb'))
            file_mimetype = mimetypes.guess_type(file_path)
            response = HttpResponse(file_wrapper, content_type=file_mimetype)
            response['X-Sendfile'] = file_path
            response['Content-Length'] = os.stat(file_path).st_size
            response['Content-Disposition'] = 'attachment; filename=%s' % smart_str(file_name)
            return response

chemflow/users/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse
from django.views.generic import DetailView, ListView, RedirectView, UpdateView

User = get_user_model()


class UserDetailView(LoginRequiredMixin, DetailView):

    model = User
    slug_field = "username"
    slug_url_kwarg = "username"


user_detail_view = UserDetailView.as_view()


class UserListView(LoginRequiredMixin, ListView):

    model = User
    slug_field = "username"
    slug_url_kwarg = "username"


user_list_view = UserListView.as_view()


class UserUpdateView(LoginRequiredMixin, UpdateView):

    model = User
    fields = ["name"]

    def get_success_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})

    def get_object(self):
        return User.objects.get(username=self.request.user.username)


user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):

    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})


user_redirect_view = UserRedirectView.as_view()

chemflow/templates/403_csrf.html
{% extends "base.html" %}

{% block title %}Forbidden (403){% endblock %}

{% block content %}
<h1>Forbidden (403)</h1>

<p>CSRF verification failed. Request aborted.</p>
{% endblock content %}

chemflow/templates/base.html
{% load static i18n %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>{% block title %}ChemFlow{% endblock title %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.min.js"></script>
    <![endif]-->

    <link rel="icon" href="{% static 'images/favicons/logo.png' %}">

    {% block css %}
    
    <!-- Latest compiled and minified Bootstrap 4.1.1 CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.2.0/css/all.css" integrity="sha384-hWVjflwFxL6sNzntih27bfxkr27PmbbK/iSvJ+a4+0owXq79v+lsFkW54bOGbiDQ" crossorigin="anonymous">

    <!-- Your stuff: Third-party CSS libraries go here -->
    
    <!-- This file stores project-specific CSS -->
    
    <link href="{% static 'css/project.css' %}" rel="stylesheet">
    <link href="{% static 'css/table.css' %}" rel="stylesheet">

    {% endblock %}

    {% block css_spe %}
    {% endblock %}

  </head>

  <body>

    <div class="m-b-1">
      <nav class="navbar navbar-expand-md navbar-light bg-light">
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <a class="navbar-brand" href="{% url 'home' %}">ChemFlow</a>

        <div class="collapse navbar-collapse w-100 order-1 order-md-0 dual-collapse2" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'home' %}">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'about' %}">About</a>
            </li>
            {% if request.user.is_authenticated %}
              {% if request.user.is_superuser %}
                <li class="nav-item">
                  {# URL for jobs #}
                  <a class="nav-link" href="{% url 'users:list' %}">{% trans "Users" %}</a>
                </li>
              {% endif %}
              {% if request.user.is_superuser %}
                <li class="nav-item">
                  {# URL for jobs #}
                  <a class="nav-link" href="{% url 'jobs:list' %}">{% trans "Jobs" %}</a>
                </li>
              {% else %}
                <li class="nav-item">
                  {# URL for jobs #}
                  <a class="nav-link" href="{% url 'jobs:list' %}">{% trans "My jobs" %}</a>
                </li>
              {% endif %}
            {% endif %}
          </ul>
        </div>
        <div class="navbar-collapse collapse w-100 order-3 dual-collapse2">
          <ul class="navbar-nav ml-auto">
             {% if request.user.is_authenticated %}
              <li class="nav-item">
                {# URL provided by django-allauth/account/urls.py #}
                <a class="nav-link" href="{% url 'users:detail' request.user.username  %}">{% trans "My Profile" %}</a>
              </li>
              <li class="nav-item nav-right">
                {# URL provided by django-allauth/account/urls.py #}
                <a class="nav-link" href="{% url 'account_logout' %}">{% trans "Log Out" %}</a>
              </li>
            {% else %}
              <li class="nav-item nav-right">
                {# URL provided by django-allauth/account/urls.py #}
                <a id="sign-up-link" class="nav-link" href="{% url 'account_signup' %}">{% trans "Sign Up" %}</a>
              </li>
              <li class="nav-item nav-right">
                {# URL provided by django-allauth/account/urls.py #}
                <a id="log-in-link" class="nav-link" href="{% url 'account_login' %}">{% trans "Log In" %}</a>
              </li>
            {% endif %}
          </ul>
        </div>
      </nav>

    </div>

    <div class="container">

      {% if messages %}
          {% for message in messages %}
              <div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %}">{{ message }}</div>
          {% endfor %}
      {% endif %}

      {% block content %}
        <p>Use this document as a way to quick start any new project.</p>
      {% endblock content %}

    </div> <!-- /container -->

    {% block modal %}{% endblock modal %}

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    {% block javascript %}

      <!-- Required by Bootstrap v4.1.1 -->
      <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
      <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>

      <!-- Your stuff: Third-party javascript libraries go here -->


      <!-- place project specific Javascript in this file -->
    {% endblock javascript %}

    {% block javascript_spe %}
    {% endblock javascript_spe %}

  </body>
</html>
 