chemflow/jobs/urls.py
from django.urls import path
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from chemflow.jobs.views import (
    job_list_view,
    job_create_dock_view,
    job_create_score_view,
    job_detail_view,
    job_delete_view
)

app_name = "jobs"
urlpatterns = [
    path("", view=job_list_view, name="list"),
    path("new/docking", view=job_create_dock_view, name="create_dock"),
    path("new/rescoring", view=job_create_score_view, name="create_score"),
    path("<str:pk>/", view=job_detail_view, name="detail"),
    path("<str:pk>/delete", view=job_delete_view, name="delete"),
]

urlpatterns += staticfiles_urlpatterns()

chemflow/users/urls.py
from django.urls import path

from chemflow.users.views import (
    user_list_view,
    user_redirect_view,
    user_update_view,
    user_detail_view,
)

app_name = "users"
urlpatterns = [
    path("", view=user_list_view, name="list"),
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

config/urls.py
from django.conf import settings
from django.urls import include, path
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views

urlpatterns = [
    path("", TemplateView.as_view(template_name="pages/home.html"), name="home"),
    path(
        "about/",
        TemplateView.as_view(template_name="pages/about.html"),
        name="about",
    ),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # Job management
    path(
        "jobs/",
        include("chemflow.jobs.urls", namespace="jobs")
    ),
    # User management
    path(
        "users/",
        include("chemflow.users.urls", namespace="users"),
    ),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
] + static(
    settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

chemflow/jobs/models.py
import os
from django.db import models
from django.conf import settings
from django_celery_results.models import TaskResult

# from .tasks import run_dock, run_score


def user_directory_path(instance, filename):
    # file will be uploaded to MEDIA_ROOT/user_<id>/<filename>
    return f'user_{instance.owner.username}/{filename}'


class Job(models.Model):
    job_type = models.CharField(max_length=50, blank=True)
    job_name = models.CharField(max_length=100,  blank=True)
    project_name = models.CharField(max_length=50, blank=True)
    protocol_name = models.CharField(max_length=50, blank=True)
    sf = models.CharField(max_length=50, default='vina')

    receptor_file = models.FileField(upload_to=user_directory_path)
    receptor_name = models.CharField(max_length=100,  blank=True)
    ligands_file = models.FileField(upload_to=user_directory_path)
    ligands_name = models.CharField(max_length=100, blank=True)

    center_x = models.FloatField(blank=True, null=True)
    center_y = models.FloatField(blank=True, null=True)
    center_z = models.FloatField(blank=True, null=True)

    radius = models.FloatField(blank=True, null=True)

    size_x = models.FloatField(blank=True, null=True)
    size_y = models.FloatField(blank=True, null=True)
    size_z = models.FloatField(blank=True, null=True)

    created_at = models.DateTimeField(auto_now_add=True, blank=True)
    updated_at = models.DateTimeField(auto_now=True, blank=True)
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, blank=True)
    state = models.CharField(max_length=50, default='0')
    job_task = models.CharField(max_length=100, blank=True, null=True)
    postprocess_task = models.CharField(max_length=100, blank=True, null=True)

    def __str__(self):
        return self.job_name

    def save(self, force_insert=False, force_update=False, using=None,
             update_fields=None):
        super(Job, self).save(force_insert=False, force_update=False, using=None,
                              update_fields=None)

        if self.state == 'RUNNING':
            try:
                self.state = TaskResult.objects.get(task_id=self.job_task).status
                self.save()
            except TaskResult.DoesNotExist:
                pass

        elif self.state == 'POST PROCESSING':
            if self.postprocess_task:
                try:
                    state = TaskResult.objects.get(task_id=self.postprocess_task).status
                    if state == 'SUCCESS':
                        self.state = 'POST PROCESS'
                        self.save()
                except TaskResult.DoesNotExist:
                    pass

chemflow/users/forms.py
from django.contrib.auth import get_user_model, forms
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _

User = get_user_model()


class UserChangeForm(forms.UserChangeForm):

    class Meta(forms.UserChangeForm.Meta):
        model = User


class UserCreationForm(forms.UserCreationForm):

    error_message = forms.UserCreationForm.error_messages.update(
        {"duplicate_username": _("This username has already been taken.")}
    )

    class Meta(forms.UserCreationForm.Meta):
        model = User

    def clean_username(self):
        username = self.cleaned_data["username"]

        try:
            User.objects.get(username=username)
        except User.DoesNotExist:
            return username

        raise ValidationError(self.error_messages["duplicate_username"])

chemflow/jobs/views.py
import os
import shutil
import tarfile
from wsgiref.util import FileWrapper
import mimetypes

from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import DetailView, ListView, CreateView, DeleteView
from django.urls import reverse
from django.conf import settings
from django.http import HttpResponse
from django.utils.encoding import smart_str

from .models import Job
from .forms import JobDockForm, JobScoreForm
from .tasks import run_dock, run_score, postprocess_dock, postprocess_score


class JobCreateView(LoginRequiredMixin, CreateView):
    model = Job
    slug_field = "job_type"
    slug_url_kwarg = "job_type"

    def post(self, request, *args, **kwargs):
        request.POST = request.POST.copy()
        request.POST['owner'] = request.user.id
        request.POST['state'] = '0'
        request.POST['job_name'] = request.POST.get('project_name') + " - " + request.POST.get('protocol_name')
        request.POST['receptor_name'] = str(request.FILES['receptor_file']).split('.')[0]
        request.POST['ligands_name'] = str(request.FILES['ligands_file']).split('.')[0]
        return super(JobCreateView, self).post(request, *args, **kwargs)

    def get_success_url(self):
        return reverse("jobs:list")

    def form_valid(self, form):
        user_jobs = list(Job.objects.filter(owner=self.request.user,
                                            job_type=self.request.POST.get('job_type'),
                                            job_name=self.request.POST.get('job_name')))
        if len(user_jobs) > 0:
            form.add_error('job_name', u'You already have a job with the same name. Please change the project or protocol name.')
            return self.form_invalid(form)

        return super(JobCreateView, self).form_valid(form)


class JobCreateDockView(JobCreateView):
    form_class = JobDockForm

    def post(self, request, *args, **kwargs):
        request.POST = request.POST.copy()
        request.POST['job_type'] = 'dock'

        return super(JobCreateDockView, self).post(request, *args, **kwargs)

    def form_valid(self, form):
        return super(JobCreateDockView, self).form_valid(form)


job_create_dock_view = JobCreateDockView.as_view()


class JobCreateScoreView(JobCreateView):
    form_class = JobScoreForm

    def post(self, request, *args, **kwargs):
        request.POST = request.POST.copy()
        request.POST['job_type'] = 'score'

        return super(JobCreateScoreView, self).post(request, *args, **kwargs)

    def form_valid(self, form):
        return super(JobCreateScoreView, self).form_valid(form)


job_create_score_view = JobCreateScoreView.as_view()


class JobListView(LoginRequiredMixin, ListView):
    model = Job
    slug_field = "job_name"
    slug_url_kwarg = "job_name"

    def get(self, request, *args, **kwargs):
        for object in self.get_queryset():
            if object.state == '0':
                workdir = os.path.join(settings.MEDIA_ROOT, 'user_' + object.owner.username)
                project_name = object.project_name
                protocol_name = object.protocol_name
                receptor_file_path = os.path.basename(str(object.receptor_file))
                ligands_file_path = os.path.basename(str(object.ligands_file))
                center_x = str(object.center_x)
                center_y = str(object.center_y)
                center_z = str(object.center_z)
                sf = object.sf
                if object.job_type == 'dock':
                    job = run_dock.delay(workdir,
                                         project_name,
                                         protocol_name,
                                         receptor_file_path,
                                         ligands_file_path,
                                         center_x,
                                         center_y,
                                         center_z,
                                         sf)
                else:
                    job = run_score.delay(workdir,
                                          project_name,
                                          protocol_name,
                                          receptor_file_path,
                                          ligands_file_path,
                                          center_x,
                                          center_y,
                                          center_z,
                                          sf)
                # TODO: put the PENDING status here and change it to RUNNING when the task is RUNNING (task.py)
                object.state = "RUNNING"
                object.job_task = str(job)
                object.save()
            else:
                object.save()
        return super(JobListView, self).get(request, *args, **kwargs)


job_list_view = JobListView.as_view()


class JobDetailView(LoginRequiredMixin, DetailView):
    model = Job
    slug_field = "job_name"
    slug_url_kwarg = "job_name"

    def get(self, request, *args, **kwargs):
        object = self.get_object()
        object.save()
        workdir = os.path.join(settings.MEDIA_ROOT, 'user_' + object.owner.username)
        receptor_file_path = os.path.basename(str(object.receptor_file))
        ligands_file_path = os.path.basename(str(object.ligands_file))

        if request.GET.get('postprocess'):
            if object.job_type == 'dock':
                postprocess = postprocess_dock.delay(workdir,
                                                     object.project_name,
                                                     object.protocol_name,
                                                     receptor_file_path,
                                                     ligands_file_path,
                                                     object.center_x,
                                                     object.center_y,
                                                     object.center_z,
                                                     object.sf)
            else:
                postprocess = postprocess_score.delay(workdir,
                                                      object.project_name,
                                                      object.protocol_name,
                                                      receptor_file_path,
                                                      ligands_file_path,
                                                      object.center_x,
                                                      object.center_y,
                                                      object.center_z,
                                                      object.sf)
            object.postprocess_task = str(postprocess)
            object.state = 'POST PROCESSING'
            object.save()

        if request.GET.get('download'):
            pass
            # Compress the results in a tar file
            # tar = tarfile.open("sample.tar.bz2", "w:bz2")
            # for name in ["file1", "file2", "file3"]:
            #     tar.add(name)
            # tar.close()

        if request.GET.get('download_receptor'):
            file_path = os.path.join(workdir, receptor_file_path)
            file_wrapper = FileWrapper(open(file_path, 'rb'))
            file_mimetype = mimetypes.guess_type(file_path)
            response = HttpResponse(file_wrapper, content_type=file_mimetype)
            response['X-Sendfile'] = file_path
            response['Content-Length'] = os.stat(file_path).st_size
            response['Content-Disposition'] = 'attachment; filename=%s' % smart_str(object.receptor_name + '.' + receptor_file_path.split('.')[-1])
            return response

        if request.GET.get('download_ligands'):
            file_path = os.path.join(workdir, ligands_file_path)
            file_wrapper = FileWrapper(open(file_path, 'rb'))
            file_mimetype = mimetypes.guess_type(file_path)
            response = HttpResponse(file_wrapper, content_type=file_mimetype)
            response['X-Sendfile'] = file_path
            response['Content-Length'] = os.stat(file_path).st_size
            response['Content-Disposition'] = 'attachment; filename=%s' % smart_str(object.ligands_name + '.' + ligands_file_path.split('.')[-1])
            return response

        if request.GET.get('download_docking'):
            file_path = os.path.join(workdir, object.project_name + '.chemflow', 'DockFlow', object.protocol_name, receptor_file_path.split('.')[0], 'docked_ligands.mol2')
            file_wrapper = FileWrapper(open(file_path, 'rb'))
            file_mimetype = mimetypes.guess_type(file_path)
            response = HttpResponse(file_wrapper, content_type=file_mimetype)
            response['X-Sendfile'] = file_path
            response['Content-Length'] = os.stat(file_path).st_size
            response['Content-Disposition'] = 'attachment; filename=%s' % smart_str('docked_ligands.mol2')
            return response

        if request.GET.get('download_energy'):
            if object.job_type == 'dock':
                file_path = os.path.join(workdir, object.project_name + '.chemflow', 'DockFlow', object.protocol_name, receptor_file_path.split('.')[0], 'DockFlow.csv')
                file_name = 'DockFlow.csv'
            else:
                file_path = os.path.join(workdir, object.project_name + '.chemflow', 'ScoreFlow', object.protocol_name, receptor_file_path.split('.')[0], 'ScoreFlow.csv')
                file_name = 'ScoreFlow.csv'
            file_wrapper = FileWrapper(open(file_path, 'rb'))
            file_mimetype = mimetypes.guess_type(file_path)
            response = HttpResponse(file_wrapper, content_type=file_mimetype)
            response['X-Sendfile'] = file_path
            response['Content-Length'] = os.stat(file_path).st_size
            response['Content-Disposition'] = 'attachment; filename=%s' % smart_str(file_name)
            return response

chemflow/users/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse
from django.views.generic import DetailView, ListView, RedirectView, UpdateView

User = get_user_model()


class UserDetailView(LoginRequiredMixin, DetailView):

    model = User
    slug_field = "username"
    slug_url_kwarg = "username"


user_detail_view = UserDetailView.as_view()


class UserListView(LoginRequiredMixin, ListView):

    model = User
    slug_field = "username"
    slug_url_kwarg = "username"


user_list_view = UserListView.as_view()


class UserUpdateView(LoginRequiredMixin, UpdateView):

    model = User
    fields = ["name"]

    def get_success_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})

    def get_object(self):
        return User.objects.get(username=self.request.user.username)


user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):

    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})


user_redirect_view = UserRedirectView.as_view()

chemflow/templates/jobs/job_confirm_delete.html
{% extends "base.html" %}
{% load static i18n %}
{% block title %}ChemFlow | Delete {{ object.job_name }}{% endblock %}

{% block content %}
<div class="container">
  <h2>Delete {{ object.job_name }}</h2>

  <div>
    <form method="post">
      {% csrf_token %}
        <p>Are you sure you want to delete job "{{ object }}"?</p>
        <input type="submit" class="btn btn-primary" value="Confirm">
        <a href="{% url 'jobs:list' %}">
          <button type="button" class="btn btn--default">Cancel</button>
        </a>
    </form>
  </div>
</div>
{% endblock content %}

chemflow/templates/jobs/job_detail.html
{% extends "base.html" %}
{% load static i18n %}
{% block title %}ChemFlow | {{ object.job_name }}{% endblock %}

{% block content %}
  <h2>{% if object.job_type == 'dock' %} Docking:{% else %} Scoring:{% endif %} {{ object.job_name }}</h2>

  <div class="container">
    <div class="row">
      <div class="m-2" style="float:left; width:45%;">
        <h4>Summary: </h4>
        <div class="row">
          <div class="col-md-8 m-2">
            Project : {{ object.project_name }}
          </div>
        </div>
        <div class="row">
          <div class="col-md-8 m-2">
            Protocol : {{ object.protocol_name }}
          </div>
        </div>
        <div class="row">
          <div class="col-md-8 m-2">
            Scoring function : {{ object.sf }}
          </div>
        </div>
        <div class="row">
          <div class="col-md-8 m-2">
            Receptor : {{ object.receptor_name }}
            <form style="display:inline-block;" action="{% url 'jobs:detail' job.pk %}" method="get">
                <button type="submit" class="btn btn--default" name="download_receptor" value="true">
                   <span class="fas fa-download" aria-hidden="true"></span>
                </button>
            </form>
          </div>
        </div>
        <div class="row">
          <div class="col-md-8 m-2">
            Ligands : {{ object.ligands_name }}
            <form style="display:inline-block;" action="{% url 'jobs:detail' job.pk %}" method="get">
                <button type="submit" class="btn btn--default" name="download_ligands" value="true">
                    <span class="fas fa-download" aria-hidden="true"></span>
                </button>
            </form>
          </div>
        </div>
        {% if object.sf != 'mmgbsa' %}
          <div class="row">
            <div class="col-md-8 m-2">
              center_x : {{ object.center_x }}
            </div>
          </div>
          <div class="row">
            <div class="col-md-8 m-2">
              center_y : {{ object.center_y }}
            </div>
          </div>
          <div class="row">
            <div class="col-md-8 m-2">
              center_z : {{ object.center_z }}
            </div>
          </div>
          {% if object.sf != 'vina' %}
            <div class="row">
              <div class="col-md-8 m-2">
                radius : {{ object.radius }}
              </div>
            </div>
          {% endif %}
          {% if object.sf == 'vina' %}
            <div class="row">
              <div class="col-md-8 m-2">
                size_x : {{ object.size_x }}
              </div>
            </div>
            <div class="row">
              <div class="col-md-8 m-2">
                size_y : {{ object.size_y }}
              </div>
            </div>
            <div class="row">
              <div class="col-md-8 m-2">
                size_z : {{ object.size_z }}
              </div>
            </div>
          {% endif %}
        {% endif %}
        <div class="row">
          <div class="col-md-8 m-2">
            state : {{ object.state }}
          </div>
        </div>
      </div>
      <div style="float:left; width: 45%;">
        {% if object.state == 'SUCCESS' %}
          <div class="m-2">
            <form action="{% url 'jobs:detail' job.pk %}" method="get">
                <button type="submit" class="btn btn--default" name="postprocess" value="true">Post-process</button>
            </form>
          </div>
        {% elif  object.state == 'POST PROCESS' %}
          <div class="row">
            <div class="m-2">
              <button type="submit" class="btn btn--default" name="status" value="post-process" disabled>Post-processed</button>
            </div>
            <div class="m-2">
              <form action="{% url 'jobs:detail' job.pk %}" method="get">
                  <button type="submit" class="btn btn--default" name="download" value="true">
                     <span class="fas fa-download" aria-hidden="true"></span>
                  </button>
              </form>
            </div>
          </div>
          {% if object.job_type == 'dock' %}
          <div class="row">
            <div class="m-2">
              <form style="display:inline-block;" action="{% url 'jobs:detail' job.pk %}" method="get">
                  <button type="submit" class="btn btn--default" name="download_docking" value="true">
                      Docking results <span class="fas fa-download" aria-hidden="true"></span>
                  </button>
              </form>
            </div>
          </div>
          {% endif%}
          <div class="row">
            <div class="m-2">
              <form style="display:inline-block;" action="{% url 'jobs:detail' job.pk %}" method="get">
                  <button type="submit" class="btn btn--default" name="download_energy" value="true">
                      Energy results <span class="fas fa-download" aria-hidden="true"></span>
                  </button>
              </form>
            </div>
          </div>
        {% else %}
        <div class="row">
          <div class="m-2">
            <button type="submit" class="btn btn--default" name="status" value="post-process" disabled>Post-process</button>
          </div>
        </div>
        {% endif %}
      </div>
    </div>
  </div>
{% endblock content %}

chemflow/templates/jobs/job_list.html
{% extends "base.html" %}
{% load staticfiles %}
{% block title %}ChemFlow - Jobs{% endblock %}


{% block css_spe %}
  <link rel="stylesheet" href="{% static 'css/table.css' %}">
{% endblock %}

{% block content %}
<div class="container">
  <h2>Jobs</h2>

  <div class="my-2">
    <a href="{% url 'jobs:create_dock' %}">
      <button type="button" class="btn btn-default">
        <span class="fas fa-plus" aria-hidden="true"></span>
        New docking
      </button>
    </a>
    <a href="{% url 'jobs:create_score' %}">
      <button type="button" class="btn btn-default">
        <span class="fas fa-plus" aria-hidden="true"></span>
        New rescoring
      </button>
    </a>
  </div>

  <div class="py-5" >
    <div class="row">
      <div class="panel panel-primary filterable">
        <div class="panel-heading">
          <h3 class="panel-title">Dockings</h3>
          <div class="pull-right" style="float:right">
            <button class="btn btn-default btn-xs btn-filter"><span class="fas fa-search"></span> Filter</button>
          </div>
        </div>
        <table class="table">
          <thead>
            <tr class="filters">
              <th>
                <input type="text" class="form-control" placeholder="Job name" disabled="disabled"> </th>
              <th style="width:200px;">
                <input type="text" class="form-control" placeholder="receptor" disabled="disabled"> </th>
              <th style="width:200px;">
                <input type="text" class="form-control" placeholder="ligands" disabled="disabled"> </th>
              <th>
                <input type="text" class="form-control" placeholder="date" disabled="disabled"> </th>
              <th style="width:150px;">
                <input type="text" class="form-control" placeholder="state" disabled="disabled"> </th>
              <th style="width:130px"></th>
            </tr>
          </thead>
          <tbody>
          {% for job in job_list %}
              {% if job.job_type == 'dock' %}
                {% if job.owner.id == request.user.id or request.user.is_superuser %}
                <tr>
                  <td>
                    <h5 class="mb-1">{{ job.job_name }}</h5>
                  </td>
                  <td>
                    {{ job.receptor_name }}
                  </td>
                  <td>
                    {{ job.ligands_name }}
                  </td>
                  <td>
                    <small>{{ job.created_at }}</small>
                  </td>
                  <td>
                    {{ job.state }}
                  </td>
                  <td style="text-align:center">
                    <a href="{% url 'jobs:detail' job.pk %}">
                      <button type="button" class="btn btn-default" aria-label="Show">
                        <span class="far fa-eye" aria-hidden="true"></span>
                      </button>
                    </a>
                    <a href="{% url 'jobs:delete' job.pk %}">
                      <button type="button" class="btn btn-default" aria-label="Delete">
                        <span class="fas fa-trash-alt" aria-hidden="true"></span>
                      </button>
                    </a>
                  </td>
                </tr>
                {% endif %}
              {% endif %}
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
  </div>

  <div class="py-5" >
    <div class="row">
      <div class="panel panel-primary filterable">
        <div class="panel-heading">
          <h3 class="panel-title">Rescorings</h3>
          <div class="pull-right" style="float:right">
            <button class="btn btn-default btn-xs btn-filter"><span class="fas fa-search"></span> Filter</button>
          </div>
        </div>
        <table class="table">
          <thead>
            <tr class="filters">
              <th>
                <input type="text" class="form-control" placeholder="Job name" disabled="disabled"> </th>
              <th style="width:200px;">
                <input type="text" class="form-control" placeholder="receptor" disabled="disabled"> </th>
              <th style="width:200px;">
                <input type="text" class="form-control" placeholder="ligands" disabled="disabled"> </th>
              <th>
                <input type="text" class="form-control" placeholder="date" disabled="disabled"> </th>
              <th style="width:150px;">
                <input type="text" class="form-control" placeholder="state" disabled="disabled"> </th>
              <th style="width:130px"></th>
            </tr>
          </thead>
          <tbody>
          {% for job in job_list %}
              {% if job.job_type == 'score' %}
                {% if job.owner.id == request.user.id or request.user.is_superuser %}
                <tr>
                  <td>
                    <h5 class="mb-1">{{ job.job_name }}</h5>
                  </td>
                  <td>
                    {{ job.receptor_name }}
                  </td>
                  <td>
                    {{ job.ligands_name }}
                  </td>
                  <td>
                    {{ job.created_at }}
                  </td>
                  <td>
                    {{ job.state }}
                  </td>
                  <td style="text-align:center">
                    <a href="{% url 'jobs:detail' job.pk %}">
                      <button type="button" class="btn btn-default" aria-label="Show">
                        <span class="far fa-eye" aria-hidden="true"></span>
                      </button>
                    </a>
                    <a href="{% url 'jobs:delete' job.pk %}">
                      <button type="button" class="btn btn-default" aria-label="Delete">
                        <span class="fas fa-trash-alt" aria-hidden="true"></span>
                      </button>
                    </a>
                  </td>
                </tr>
                {% endif %}
              {% endif %}
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
  </div>


</div>
{% endblock content %}

{% block javascript_spe %}
  <script src="{% static 'js/table.js' %}"></script>
{% endblock javascript_spe %}